# Generated by Django 4.0.4 on 2022-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
