# Generated by Django 4.0.4 on 2022-05-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_asset', '0002_alter_document_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ﾀｲﾄﾙ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
